# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_remove_twitteruser_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='following',
            field=models.ManyToManyField(blank=True, to='model.TwitterUser'),
        ),
    ]
