# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20171010_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('following', models.ManyToManyField(blank=True, to='model.InstagramUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='following',
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_twitteruser_friends_+', to='model.TwitterUser'),
        ),
    ]
