# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_auto_20171010_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
